### PR TITLE
implemented getTopUsers

### PR DESCRIPTION
**Pull request by jwahjudi**
Is it something like this?

### CODE REVIEW

**Comment by mosopeogundipe** [comment]
> 
> 
> Is it something like this?

Yes, this is how it should look! With only your changes showing up and not everyone else's bundled up into yours. Good work. Please confirm that you've tested your new API again on this branch before we allow you to merge. I can't see any Heroku review app created for it. So if you haven't, please test it & say once you're done so I can approve.

**Comment by jwahjudi** [comment]
Yes I was able to test it and got it to work. 
URL: https://hsit-fav-che-temp-yqnxsvznmkjo.herokuapp.com/getTopUsers?selected=faves&start=1&nums=10

**Comment by mosopeogundipe** [comment]
> 
> 
> Yes I was able to test it and got it to work.
> URL: https://hsit-fav-che-temp-yqnxsvznmkjo.herokuapp.com/getTopUsers?selected=faves&start=1&nums=10

Cool, then I'm fine with it

**Review by mosopeogundipe — APPROVED** [review]

**Review by kedarkhetia — APPROVED** [review]
I can see bugs in this code. But we can address the fix in another CR.

**Pull request merged**
